// astro-react/src/components/common/elements/FormField.tsx
import { useId, ComponentType } from 'react';
import { Controller, Control } from 'react-hook-form';
import type { FormField } from '../../../types/section.types';
import {
  Field,
  FieldError,
  FieldContent,
  FieldTitle,
  FieldDescription,
} from '../../../components/ui/field';
import { Label } from '../../../components/ui/label';
import { ErrorBoundary } from 'react-error-boundary';
import { Input } from '../../../components/ui/input';
import { Textarea } from '../../../components/ui/textarea';
import { Checkbox } from '../../../components/ui/checkbox';
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from '../../../components/ui/select';
import { RadioGroup, RadioGroupItem } from '../../../components/ui/radio-group';
import { ErrorHandler } from '../ErrorBoundary';

type FormFieldProps = FormField & {
  control?: Control<any>;
};

export default function FormFieldRenderer(props: FormFieldProps) {
  const id = useId();

  const getComponent = (): ComponentType<any> | null => {
    switch (props.type) {
      case 'text':
      case 'password':
      case 'email':
      case 'number':
      case 'color':
      case 'range':
      case 'file':
        return Input;

      case 'textarea':
        return Textarea;

      case 'checkbox':
        return Checkbox;

      case 'select':
        return Select;

      default:
        return null;
    }
  };

  const Component = getComponent();

  return (
    <ErrorBoundary FallbackComponent={ErrorHandler}>
      <Controller
        name={props.name}
        control={props.control}
        render={({ field, fieldState }) => {
          const hasError = !!fieldState.error;

          return (
            <Field data-invalid={hasError}>
              {/* Checkbox */}
              {props.type === 'checkbox' && (
                <div className="flex items-center gap-4">
                  <Checkbox
                    id={`checkbox-` + id}
                    checked={field.value}
                    onCheckedChange={field.onChange}
                    aria-invalid={hasError}
                  />
                  <Label htmlFor={`checkbox-` + id}>{props.label}</Label>
                </div>
              )}

              {/* Label (non-checkbox) */}
              {props.type !== 'checkbox' && (
                <Label htmlFor={id} data-test-field={props['test-field']}>
                  {props.label}
                </Label>
              )}

              {/* Radio */}
              {props.type === 'radio' && (
                <RadioGroup
                  id={`radiogroup-` + id}
                  name={props.name}
                  value={field.value}
                  onValueChange={field.onChange}
                  aria-invalid={hasError}
                >
                  {props.options?.map((option) => (
                    <Label
                      key={option.value}
                      htmlFor={`form-radio-${option.value}`}
                    >
                      <Field orientation="horizontal" data-invalid={hasError}>
                        <FieldContent>
                          <FieldTitle>{option.label}</FieldTitle>
                          {option?.desc && (
                            <FieldDescription>{option.desc}</FieldDescription>
                          )}
                        </FieldContent>

                        <RadioGroupItem
                          id={`form-radio-${option.value}`}
                          value={option.value}
                          aria-invalid={hasError}
                        />
                      </Field>
                    </Label>
                  ))}
                </RadioGroup>
              )}

              {/* Select */}
              {props.type === 'select' && (
                <Select value={field.value} onValueChange={field.onChange}>
                  <SelectTrigger
                    id={id}
                    className="w-full"
                    aria-invalid={hasError}
                  >
                    <SelectValue placeholder={props.placeholder} />
                  </SelectTrigger>
                  <SelectContent>
                    {props.options?.map((option) => (
                      <SelectItem
                        key={option.value}
                        value={option.value ?? 'empty'}
                      >
                        {option.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}

              {/* DEFAULT INPUT */}
              {!['checkbox', 'select', 'radio'].includes(`${props.type}`) &&
                Component && (
                  <Component
                    className="placeholder:text-inherit/90"
                    {...field}
                    id={`input-` + id}
                    type={props.type}
                    placeholder={props.placeholder}
                    aria-invalid={hasError}
                  />
                )}

              {/* ERROR */}
              {fieldState.error && (
                <FieldError>{fieldState.error.message}</FieldError>
              )}
            </Field>
          );
        }}
      />
    </ErrorBoundary>
  );
}

// nuxt/app/components/common/elements/FormField.vue
<script setup lang="ts">
import { useId, computed } from 'vue';
import type { FormField } from '@/types/section.types';
import { Field as VeeField } from 'vee-validate';
import { cn } from '@/utils';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Textarea } from '@/components/ui/textarea';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectTrigger,
  SelectContent,
  SelectValue,
  SelectItem,
} from '@/components/ui/select';
import {
  Field,
  FieldLabel,
  FieldContent,
  FieldDescription,
  FieldTitle,
  FieldError,
} from '@/components/ui/field';

const props = defineProps<FormField>();
const id = useId();

const formFieldComponent = computed(() => {
  switch (props.type) {
    case 'text': {
      return Input;
    }
    case 'email': {
      return Input;
    }
    case 'password': {
      return Input;
    }
    case 'checkbox': {
      return Checkbox;
    }
    case 'number': {
      return Input;
    }
    case 'textarea': {
      return Textarea;
    }
    case 'color': {
      return Input;
    }
    case 'range': {
      return Input;
    }
    case 'file': {
      return Input;
    }
    case 'select': {
      return Select;
    }

    default:
      break;
  }
});
</script>

<template>
  <VeeField v-slot="{ field, errors }" :name="props.name">
    <Field :data-invalid="!!errors.length">
      <!-- Label for Checkbox -->
      <div class="flex items-center gap-4" v-if="props.type === 'checkbox'">
        <Checkbox :id="id" v-bind="field" :aria-invalid="!!errors.length" />
        <Label :for="id">
          {{ props.label }}
        </Label>
      </div>
      <!-- Label for all other fields -->
      <FieldLabel v-else :for="id"> {{ props.label }} </FieldLabel>

      <!-- RADIO FIELD  -->
      <RadioGroup
        :id="id"
        v-if="props.type === 'radio'"
        :name="props.name"
        :model-value="field.value"
        :aria-invalid="!!errors.length"
        @update:model-value="field.onChange"
      >
        <FieldLabel
          v-for="option in props?.options || []"
          :key="option.value"
          :for="`form-vee-radiogroup-${option.value}`"
        >
          <Field orientation="horizontal" :data-invalid="!!errors.length">
            <FieldContent>
              <FieldTitle>{{ option.label }}</FieldTitle>
              <FieldDescription v-if="option?.desc">
                {{ option?.desc }}
              </FieldDescription>
            </FieldContent>
            <RadioGroupItem
              :id="`form-vee-radiogroup-${option.value}`"
              :value="option.value"
              :aria-invalid="!!errors.length"
            />
          </Field>
        </FieldLabel>
      </RadioGroup>

      <!-- SELECT FIELD -->
      <Select
        :id="id"
        :name="props.name"
        :type="props.type"
        v-model="field.value"
        @blur="field.onBlur"
        @update:model-value="field.onChange"
        v-if="props.type === 'select'"
      >
        <SelectTrigger :class="cn('w-full')" :aria-invalid="!!errors.length">
          <SelectValue :placeholder="props.placeholder" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem
            v-for="option in props.options"
            :value="option.value || 'empty'"
            >{{ option.label }}</SelectItem
          >
        </SelectContent>
      </Select>

      <!-- TEXT, EMAIL, PASSWORD, NUMBER, TEXTAREA, COLOR, RANGE, FILE, ETC FIELDS -->
      <component
        v-else-if="!['checkbox', 'select', 'radio'].includes(`${props.type}`)"
        :is="formFieldComponent"
        class="placeholder:text-inherit/90"
        :id="id"
        v-bind="field"
        :placeholder="props.placeholder"
        :type="props.type"
        :aria-invalid="!!errors.length"
      />

      <!-- ERROR MESSAGE -->
      <FieldError v-if="errors.length">
        <div v-for="error in errors" :key="error">
          {{ error }}
        </div>
      </FieldError>
    </Field>
  </VeeField>
</template>
