// nuxt/app/components/common/elements/ImageElement.vue
<script setup lang="ts">
import type { ImageEle } from '@/types/section.types';
import { computed } from 'vue';
import RenderBackgrounds from '../RenderBackgrounds.vue';
import { DEFAULT_CLASSES, DEFAULT_PLACEHOLDER_IMG } from '../../../constants';
import { cn, getEleAnimation } from '@/utils';

const { class: classList, ...restProps } = defineProps<ImageEle>();

/**
 * Alt tag Attribute
 */
const altTag = computed(() => (restProps.alt || 'image') as string);

/**
 * Class Attribute
 */
const classes = computed(() =>
  cn(
    Object.values(DEFAULT_CLASSES?.img || {}).join(' '), // base
    classList
  )
);

/**
 * Props
 */
const imageProps = computed(() => ({
  ...restProps,
  alt: altTag.value,
  src: restProps.src ?? DEFAULT_PLACEHOLDER_IMG,
}));

/**
 * Animation
 * returns {
 *   component: img or motion.create(img)
 *   details: animation props
 * }
 */
const animation = computed(() => getEleAnimation('image', restProps.animation));

const backgrounds = computed(() => restProps.backgrounds ?? []);
</script>

<template>
  <!-- main image -->
  <component
    :is="animation.component"
    v-bind="{ ...imageProps, ...animation.details }"
    :class="classes"
    loading="lazy"
  />
  <!-- image backgrounds -->
  <div
    v-if="backgrounds?.length > 0"
    :class="cn('absolute inset-0 -z-1', classes)"
  >
    <RenderBackgrounds :backgrounds="backgrounds" :render-color-scheme="true" />
  </div>
</template>

// astro-react/src/components/common/elements/ImageElement.tsx
import { useMemo } from 'react';
import type { ImageEle } from '../../../types/section.types';
import { cn, getEleAnimation } from '../../../utils';
import { DEFAULT_CLASSES } from '../../../constants';
import RenderBackgrounds from '../RenderBackgrounds';

export default function ImageElement(props: ImageEle) {
  const { className, ...rest } = props;

  // Compute image element CSS classes
  const classes = cn(
    Object.values(DEFAULT_CLASSES?.img || {}).join(' '),
    className
  );

  // Resolve component type and animation details
  const { Component, details: animationDetails } = useMemo(() => {
    return getEleAnimation('image', props.animation, 'img');
  }, [props.animation]);

  const backgrounds = props.backgrounds ?? [];

  // Render image component (standard img or motion.img)
  return (
    <>
      {/* image backgrounds */}
      <Component
        {...animationDetails}
        {...rest}
        className={classes}
        alt={props.alt ?? 'image'}
        loading="lazy"
      />

      {/* main image backgrounds */}
      {backgrounds.length > 0 && (
        <div className={cn('absolute inset-0 -z-1', classes)}>
          <RenderBackgrounds
            backgrounds={backgrounds}
            renderColorScheme={true}
          />
        </div>
      )}
    </>
  );
}
