// react/src/pages/Pricing.tsx
import type { Page } from '@/types';
import { FC } from 'react';
import FullPageLayout from '@/layouts/FullPageLayout';
import PageWrapper from '@/components/common/PageWrapper';
import Navbar from '@/components/sections/global/Navbar.tsx';
import Pricing from '@/components/sections/pricing/Pricing.tsx';
import Testimonial from '@/components/sections/pricing/Testimonial.tsx';
import Footer from '@/components/sections/global/Footer.tsx';

const Pricing1: FC = () => {
  const page = {
    id: 'pricing',
    label: 'Pricing',
    desc: 'Information about different subscription plans and pricing options.',
    link: 'pricing',
  } as Page;

  return (
    <FullPageLayout>
      <PageWrapper page={page}>
        {/* Page Sections */}
        <Navbar />
        <Pricing />
        <Testimonial />
        <Footer />
      </PageWrapper>
    </FullPageLayout>
  );
};

export default Pricing1;

// nuxt/app/pages/pricing/index.vue
<script setup lang="ts">
import type { Page } from '@/types';
import PageWrapper from '@/components/common/PageWrapper.vue';

import Navbar from '@/components/sections/global/Navbar.vue';
import Pricing from '@/components/sections/pricing/Pricing.vue';
import Testimonial from '@/components/sections/pricing/Testimonial.vue';
import Footer from '@/components/sections/global/Footer.vue';

const page = {
  seo: {
    title: '',
    description: '',
  },
  id: 'pricing',
  link: 'pricing',
  sections: [],
} as Page;

definePageMeta({
  layout: 'full-page-layout',
  seo: page.seo,
});
</script>

<template>
  <PageWrapper :page="page">
    <!-- Sections -->
    <Navbar />
    <Pricing />
    <Testimonial />
    <Footer />
  </PageWrapper>
</template>
