// nuxt/app/pages/index.vue
<script setup lang="ts">
import type { Page } from '@/types';
import PageWrapper from '@/components/common/PageWrapper.vue';

import Navbar from '@/components/sections/global/Navbar.vue';
import Hero from '@/components/sections/home/Hero.vue';
import Feature from '@/components/sections/home/Feature.vue';
import HowItWorks from '@/components/sections/home/HowItWorks.vue';
import Stat from '@/components/sections/home/Stat.vue';
import Testimonial from '@/components/sections/home/Testimonial.vue';
import Integration from '@/components/sections/home/Integration.vue';
import Pricing from '@/components/sections/home/Pricing.vue';
import Cta from '@/components/sections/home/Cta.vue';
import Footer from '@/components/sections/global/Footer.vue';

const page = {
  seo: {
    title: '',
    description: '',
  },
  id: 'home',
  link: 'home',
  sections: [],
} as Page;

definePageMeta({
  layout: 'full-page-layout',
  seo: page.seo,
});
</script>

<template>
  <PageWrapper :page="page">
    <!-- Sections -->
    <Navbar />
    <Hero />
    <Feature />
    <HowItWorks />
    <Stat />
    <Testimonial />
    <Integration />
    <Pricing />
    <Cta />
    <Footer />
  </PageWrapper>
</template>

// react/src/pages/Index.tsx
import type { Page } from '@/types';
import { FC } from 'react';
import FullPageLayout from '@/layouts/FullPageLayout';
import PageWrapper from '@/components/common/PageWrapper';
import Navbar from '@/components/sections/global/Navbar.tsx';
import Hero from '@/components/sections/home/Hero.tsx';
import Feature from '@/components/sections/home/Feature.tsx';
import HowItWorks from '@/components/sections/home/HowItWorks.tsx';
import Stat from '@/components/sections/home/Stat.tsx';
import Testimonial from '@/components/sections/home/Testimonial.tsx';
import Integration from '@/components/sections/home/Integration.tsx';
import Pricing from '@/components/sections/home/Pricing.tsx';
import Cta from '@/components/sections/home/Cta.tsx';
import Footer from '@/components/sections/global/Footer.tsx';

const Index: FC = () => {
  const page = {
    id: 'home',
    label: 'Home',
    desc: 'The main landing page of MailWavy, introducing the email marketing solution for growing businesses.',
    link: 'home',
  } as Page;

  return (
    <FullPageLayout>
      <PageWrapper page={page}>
        {/* Page Sections */}
        <Navbar />
        <Hero />
        <Feature />
        <HowItWorks />
        <Stat />
        <Testimonial />
        <Integration />
        <Pricing />
        <Cta />
        <Footer />
      </PageWrapper>
    </FullPageLayout>
  );
};

export default Index;
