// nuxt/app/components/common/ToggleMode.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import Icon from './elements/Icon.vue';

const colorMode = useColorMode();
</script>

<template>
  <div>
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button size="icon-sm" variant="ghost" aria-label="Select theme">
          <Icon
            name="Sun"
            class="h-[1.2rem] w-[1.2rem] scale-100 rotate-0 transition-all dark:scale-0 dark:-rotate-90"
          />
          <Icon
            name="Moon"
            class="absolute h-[1.2rem] w-[1.2rem] scale-0 rotate-90 transition-all dark:scale-100 dark:rotate-0"
          />
          <span class="sr-only">Toggle theme</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" class="z-[1001] min-w-32">
        <DropdownMenuItem @click="colorMode.preference = 'light'">
          <Icon name="Sun" class="size-4 opacity-60" aria-hidden="true" />
          <span>Light</span>
        </DropdownMenuItem>
        <DropdownMenuItem @click="colorMode.preference = 'dark'">
          <Icon name="Moon" class="size-4 opacity-60" aria-hidden="true" />
          <span>Dark</span>
        </DropdownMenuItem>
        <DropdownMenuItem @click="colorMode.preference = 'auto'">
          <Icon name="Monitor" class="size-4 opacity-60" aria-hidden="true" />
          <span>System</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  </div>
</template>

// react/src/components/common/ToggleMode.tsx
import { Moon, Sun } from 'lucide-react';
// custom
import { useTheme } from './ThemeProvider';
import { Button } from '../ui/button';
import { Icon } from './elements';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '../ui/dropdown-menu';

type Props = {
  className?: string;
};

export default function ModeToggle(props: Props) {
  const { setTheme } = useTheme();

  return (
    <div className={`flex items-center gap-2 ${props.className}`}>
      <DropdownMenu>
        <DropdownMenuTrigger asChild className="cursor-pointer">
          <Button size="icon" variant="ghost" aria-label="Select theme">
            <Icon
              name="Sun"
              className="h-[1.2rem] w-[1.2rem] text-current dark:hidden"
            />
            <Icon
              name="Moon"
              className="hidden h-[1.2rem] w-[1.2rem] text-current dark:block"
            />
            <span className="sr-only">Toggle theme</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem
            className="cursor-pointer"
            onClick={() => setTheme('light')}
          >
            <Icon name="Sun" /> Light
          </DropdownMenuItem>
          <DropdownMenuItem
            className="cursor-pointer"
            onClick={() => setTheme('dark')}
          >
            <Icon name="Moon" /> Dark
          </DropdownMenuItem>
          <DropdownMenuItem
            className="cursor-pointer"
            onClick={() => setTheme('system')}
          >
            <Icon name="Monitor" /> System
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}
