// next/src/components/ui/border-beam.tsx
'use client';

import { motion, MotionStyle, Transition } from 'motion/react';
import { cn } from '@/utils';

interface BorderBeamProps {
  /**
   * The size of the border beam.
   */
  size?: number;
  /**
   * The duration of the border beam.
   */
  duration?: number;
  /**
   * The delay of the border beam.
   */
  delay?: number;
  /**
   * The color of the border beam from.
   */
  colorFrom?: string;
  /**
   * The color of the border beam to.
   */
  colorTo?: string;
  /**
   * The motion transition of the border beam.
   */
  transition?: Transition;
  /**
   * The class name of the border beam.
   */
  className?: string;
  /**
   * The style of the border beam.
   */
  style?: React.CSSProperties;
  /**
   * Whether to reverse the animation direction.
   */
  reverse?: boolean;
  /**
   * The initial offset position (0-100).
   */
  borderWidth?: number;

  initialOffset?: number;
}

export const BorderBeam = ({
  borderWidth = 1.5,
  className,
  colorFrom = '#eee',
  colorTo = '#000',
  delay = 0,
  duration = 6,
  initialOffset = 0,
  reverse = false,
  size = 50,
  style,
  transition,
}: BorderBeamProps) => {
  return (
    <div
      style={
        {
          '--border-width': borderWidth,
        } as any
      }
      className="pointer-events-none absolute inset-0 rounded-[inherit] [mask-image:linear-gradient(transparent,transparent),linear-gradient(#000,#000)] [mask-composite:intersect] [mask-clip:padding-box,border-box] [border:calc(var(--border-width)*1px)_solid_transparent]"
    >
      <motion.div
        className={cn(
          'absolute aspect-square',
          'bg-gradient-to-l from-[var(--color-from)] via-[var(--color-to)] to-transparent',
          className
        )}
        style={
          {
            '--color-from': colorFrom,
            '--color-to': colorTo,
            offsetPath: `rect(0 auto auto 0 round ${size}px)`,
            width: size,

            ...style,
          } as MotionStyle
        }
        initial={{ offsetDistance: `${initialOffset}%` }}
        animate={{
          offsetDistance: reverse
            ? [`${100 - initialOffset}%`, `${-initialOffset}%`]
            : [`${initialOffset}%`, `${100 + initialOffset}%`],
        }}
        transition={{
          delay: -delay,
          duration,
          ease: 'linear',
          repeat: Infinity,
          ...transition,
        }}
      />
    </div>
  );
};

// vue/src/components/ui/BorderBeam.vue
<template>
  <div
    :class="
      cn(
        'border-beam',
        'pointer-events-none absolute inset-0 rounded-[inherit] [border:calc(var(--border-width)*1px)_solid_transparent]',
        '![mask-clip:padding-box,border-box] ![mask-composite:intersect] [mask:linear-gradient(transparent,transparent),linear-gradient(white,white)]',
        'animate-border-beam after:absolute after:aspect-square after:w-[calc(var(--size)*1px)] after:[animation-delay:var(--delay)] after:[background:linear-gradient(to_left,var(--color-from),var(--color-to),transparent)] after:[offset-anchor:calc(var(--anchor)*1%)_50%] after:[offset-path:rect(0_auto_auto_0_round_calc(var(--size)*1px))]',
        props.class,
      )
    "
  />
</template>

<script setup lang="ts">
  import { computed } from "vue";
  import { cn } from "@/utils";

  interface BorderBeamProps {
    size?: number;
    class?: string;
    delay?: number;
    anchor?: number;
    colorTo?: string;
    duration?: number;
    colorFrom?: string;
    borderWidth?: number;
  }

  const props = withDefaults(defineProps<BorderBeamProps>(), {
    anchor: 90,
    borderWidth: 1.5,
    colorFrom: "#eee",
    colorTo: "#000",
    delay: 0,
    duration: 15000,
    size: 200,
  });

  const durationInSeconds = computed(() => `${props.duration}s`);
  const delayInSeconds = computed(() => `${props.delay}s`);
</script>

<style scoped>
  .border-beam {
    --size: v-bind(size);
    --duration: v-bind(durationInSeconds);
    --anchor: v-bind(anchor);
    --border-width: v-bind(borderWidth);
    --color-from: v-bind(colorFrom);
    --color-to: v-bind(colorTo);
    --delay: v-bind(delayInSeconds);
  }

  .animate-border-beam::after {
    animation: border-beam-anim var(--duration) infinite linear;
  }

  @keyframes border-beam-anim {
    to {
      offset-distance: 100%;
    }
  }
</style>
