// next/src/components/common/ItemWrapper.tsx
import React, { useMemo } from 'react';
import { cn, getEleAnimation } from '../../utils';
import type { Background, ColorSchemeBg, ElementAnimation } from '../../types';
import RenderBackgrounds from './RenderBackgrounds';
import { DEFAULT_CLASSES } from '../../constants';

type ItemRendererProps = {
  item: {
    id: string | number;
    className?: string | string[];
    backgrounds?: Background[];
    animation?: ElementAnimation;
  };
  className?: string;
  contentClass?: string;
  children?: React.ReactNode;
};

export function ItemWrapper({
  item,
  className,
  children,
  contentClass,
}: ItemRendererProps) {
  // Resolve backgrounds from item data
  const bgs = useMemo<Background[]>(() => {
    return item?.backgrounds ?? [];
  }, [item]);

  // Determine color scheme based on backgrounds
  const colorScheme = useMemo<ColorSchemeBg | undefined>(() => {
    return Array.isArray(bgs)
      ? (bgs.find((bg) => 'shade' in bg) as ColorSchemeBg | undefined)
      : undefined;
  }, [bgs]);

  // Compute CSS classes
  const classes = useMemo(() => {
    const defaultClassesStr = Object.values(DEFAULT_CLASSES?.card || {}).join(
      ' '
    );

    return cn(
      'relative',
      defaultClassesStr,
      colorScheme?.className,
      className,
      item.className // override
    );
  }, [colorScheme, className, item]);

  // Determine Component and animation details
  const { Component, details } = useMemo(() => {
    return getEleAnimation('card', item?.animation, 'div');
  }, [item?.animation]);

  // Render component (standard div or motion.div)
  return (
    <Component {...details} className={classes}>
      <RenderBackgrounds backgrounds={bgs} />

      <div className={cn('relative z-0', contentClass)}>{children}</div>
    </Component>
  );
}

export default ItemWrapper;

// nuxt/app/components/common/ItemWrapper.vue
<script setup lang="ts">
import { cn } from '@/utils';
import { computed } from 'vue';
import type { Background, ColorSchemeBg, ElementAnimation } from '@/types';
import RenderBackgrounds from './RenderBackgrounds.vue';
import { DEFAULT_CLASSES } from '../../constants';

type ItemRenderer = {
  item: {
    backgrounds: Background[];
    class?: string;
    id: string | number;
    animation: ElementAnimation;
  };
  class?: string;
  contentClass?: string;
};
const props = defineProps<ItemRenderer>();

const bgs = computed(() => props.item.backgrounds || []);

const colorScheme = computed<ColorSchemeBg>(() =>
  Array.isArray(bgs.value)
    ? (bgs.value.find((bg) => 'shade' in bg) as ColorSchemeBg)
    : ({} as ColorSchemeBg)
);

const classes = computed(() => {
  const defaultClassesStr = Object.values(DEFAULT_CLASSES?.card || {}).join(
    ' '
  );

  return cn(
    'relative',
    defaultClassesStr,
    colorScheme.value?.class,
    props.class,
    // override all classes with item class
    props.item.class
  );
});
</script>

<template>
  <div :class="classes">
    <RenderBackgrounds :backgrounds="bgs" />

    <div :class="cn('relative z-0', contentClass)">
      <slot />
    </div>
  </div>
</template>
