// react/src/components/common/PageWrapper.tsx
import React, { useMemo } from 'react';
import type { Page } from '../../types';
import { cn } from '../../utils';
import RenderBackgrounds from './RenderBackgrounds';
import { SITE_BACKGROUNDS } from '../../constants';
import { ColorSchemeBg } from '../../types';

interface PageWrapperProps {
  page: Page;
  children?: React.ReactNode;
}

const PageWrapper: React.FC<PageWrapperProps> = ({ page, children }) => {
  // merge site + page backgrounds
  const bgs = useMemo(() => {
    return [...SITE_BACKGROUNDS, ...(page.backgrounds || [])];
  }, [page.backgrounds]);

  // find color scheme (bg with "shade" key)
  const colorScheme = useMemo(() => {
    return Array.isArray(bgs)
      ? (bgs.find((bg: any) => 'shade' in bg) as ColorSchemeBg)
      : ({} as ColorSchemeBg);
  }, [bgs]);

  return (
    <main
      data-page={page.id}
      id={page.id}
      className={cn(
        'relative mx-auto min-h-screen max-w-7xl min-w-min overflow-clip',
        colorScheme?.className
      )}
    >
      {/* Page Backgrounds */}
      {bgs?.length > 0 && <RenderBackgrounds backgrounds={bgs} />}

      {/* Page Sections Contents */}
      <div className={cn('relative', page.className)}>{children || ''}</div>
    </main>
  );
};

export default PageWrapper;

// nuxt/app/components/common/PageWrapper.vue
<script setup lang="ts">
import type { Page } from '../../types';
import { cn } from '../../utils';
import RenderBackgrounds from './RenderBackgrounds.vue';
import { SITE_BACKGROUNDS } from '../../constants';
import { computed } from 'vue';

const { page } = defineProps<{
  page: Page;
}>();

const bgs = computed(() => {
  return [...SITE_BACKGROUNDS, ...(page.backgrounds || [])];
});
const colorScheme = computed(() =>
  Array.isArray(bgs.value)
    ? bgs.value.find((bg: any) => 'shade' in bg)
    : ({} as any)
);
</script>

<template>
  <main
    :data-page="page.id"
    :id="page.id"
    :class="
      cn(
        'relative mx-auto min-h-screen max-w-7xl min-w-min overflow-clip',
        colorScheme?.class
      )
    "
  >
    <RenderBackgrounds v-if="bgs?.length > 0" :backgrounds="bgs || []" />

    <div :class="cn('relative', page.class)">
      <slot />
    </div>
  </main>
</template>
