// react/src/pages/Faq.tsx
import type { Page } from '@/types';
import { FC } from 'react';
import FullPageLayout from '@/layouts/FullPageLayout';
import PageWrapper from '@/components/common/PageWrapper';
import Navbar from '@/components/sections/global/Navbar.tsx';
import Faq from '@/components/sections/faq/Faq.tsx';
import Footer from '@/components/sections/global/Footer.tsx';

const Faqs: FC = () => {
  const page = {
    id: 'faq',
    label: 'FAQ',
    desc: 'Frequently asked questions and answers about MailWavy.',
    link: 'faq',
  } as Page;

  return (
    <FullPageLayout>
      <PageWrapper page={page}>
        {/* Page Sections */}
        <Navbar />
        <Faq />
        <Footer />
      </PageWrapper>
    </FullPageLayout>
  );
};

export default Faqs;

// vue/src/pages/Faq.vue
<script setup lang="ts">
import type { Page } from '@/types';
import FullPageLayout from '@/layouts/FullPageLayout.vue';
import PageWrapper from '@/components/common/PageWrapper.vue';

import Navbar from '@/components/sections/global/Navbar.vue';
import Faq from '@/components/sections/faq/Faq.vue';
import Footer from '@/components/sections/global/Footer.vue';

const page = {
  id: 'faq',
  label: 'FAQ',
  desc: 'Frequently asked questions and answers about MailWavy.',
  link: 'faq',
} as Page;
</script>

<template>
  <FullPageLayout>
    <PageWrapper :page="page">
      <!-- Page Sections -->
      <Navbar />
      <Faq />
      <Footer />
    </PageWrapper>
  </FullPageLayout>
</template>
