// next/src/components/common/SectionWrapper.tsx
import { cn, getEleAnimation } from '../../utils';
import React, { useMemo } from 'react';
import RenderBackgrounds from './RenderBackgrounds';
import { Section } from '../../types';

type Props = {
  section: Section;
  className?: string;
  children?: React.ReactNode;
};

export const SectionWrapper = ({ section, className, children }: Props) => {
  // Determine color scheme based on backgrounds
  const colorScheme = useMemo(() => {
    return Array.isArray(section.backgrounds)
      ? section.backgrounds.find((bg: any) => 'shade' in bg)
      : {};
  }, [section.backgrounds]);

  // Resolve component type and animation details
  const { Component, details } = useMemo(() => {
    return getEleAnimation('section', section?.animation, 'section');
  }, [section?.animation]);

  // Compute CSS classes
  const classes = cn(
    'max-w-screen relative',
    className,
    colorScheme?.className
  );

  // Render section component (standard section or motion.section)
  return (
    <Component
      {...details}
      data-section={section.id}
      id={section.id}
      className={classes}
    >
      {/* Render section backgrounds */}
      <RenderBackgrounds backgrounds={section.backgrounds || []} />

      {/* Section Contents */}
      <div className={cn('relative', section.className)}>{children}</div>
    </Component>
  );
};

export default SectionWrapper;

// astro-vue/src/components/common/SectionWrapper.vue
<script setup lang="ts">
import { cn, getEleAnimation } from '@/utils';
import { computed } from 'vue';
import type { ColorSchemeBg } from '@/types';
import RenderBackgrounds from './RenderBackgrounds.vue';

const props = defineProps<{ section: any }>();

const colorScheme = computed<ColorSchemeBg>(() =>
  Array.isArray(props.section.backgrounds)
    ? (props.section.backgrounds.find(
        (bg: ColorSchemeBg) => 'shade' in bg
      ) as ColorSchemeBg)
    : ({} as ColorSchemeBg)
);

/**
 * Animations
 *
 * returns {
 *   component: section or motion.create(section)
 *   details: animation props
 * }
 */
const animation = computed(() =>
  getEleAnimation('section', props.section?.animation)
);
</script>

<template>
  <component
    :is="animation.component"
    v-bind="animation.details"
    :data-section="section.id"
    :id="section.id"
    :class="cn('relative max-w-screen', colorScheme?.class)"
  >
    <RenderBackgrounds :backgrounds="section?.backgrounds || []" />

    <div :class="cn('relative', section.class)">
      <slot />
    </div>
  </component>
</template>
